### ISSUE TITLE
Gameshark Patcher 

### ISSUE THREAD

**Issue by andre1891** [Caslship/ZeldaOOP#1]
Hello Jason Antonio Palaios,
still doing Some great things With your gameshark patcher of 2014.
But I lost it and your Links which Hosted on Utexas is also down. Could you reupload it?

**Comment by Caslship** [comment]
@andre1891 I'll try to get it uploaded to my github sometime this week along with my other asm modifications. Nice to see someone still using my work!

**Comment by andre1891** [comment]
Thanks a lot. This sounds very good. Thanks for your help and Keep up your good work. When you upload it here could you make a User friendly tutorial With it. It is Some days ago I used it, it would be a little bit easy er for other People too

**Comment by andre1891** [comment]
Hello Jason Palacios, sorry for my impatience but youre still planing to upload it on github? Thanks. Have a nice weekend

**Comment by Caslship** [comment]
@andre1891, thanks for the reminder (legitamately forgot). I've gone and created a new repository where I'll hosting all my old mods. You can find the gameshark patcher there now: https://github.com/Caslship/z64asm
